### ISSUE TITLE
Blank canvas images in particular examples

### ISSUE THREAD

**Issue by iffsid** [probmods/dippl#11]
The guassian mixture, hidden semi-markov model, and particle filter for semi-markov random walk examples render blank images in 05-particlefilter.html

**Comment by stuhlmueller** [comment]
This was broken because you changed the interface of `DrawObject.circle` in 8e708f09f986916f6d75598fcbc7b0112264653f without updating all the places where `circle` is used.

Fixed in e601dbeaa58f1e71d9a929e057ec4929ff9f9084.

**Comment by iffsid** [comment]
Thanks for catching that!
I fixed the usage inside examples, but forgot to update chapters when I did this.
