### ISSUE TITLE
The addressing transform

### ISSUE THREAD

**Issue by bessiambre** [probmods/dippl#13]
I was reading about the automatic addressing transform based on stack-addresses. It seams to make sense in most cases but I was wondering how general this scheme is. It seems to work when you recurse or iterate over a list and you are always going over the same modeled individuals in the same order. But imagine you were modelling a bus full of tourists, trying to predict some attributes of each tourist such as hunger level after each stop (to determine when to stop to eat). 

Say the tourists like to trade seats and you decided to first predict the order of seating after each stop  and then recurse over the bus seats to predict other attributes. When trying to reuse sample from the previous trace, wouldn't it make more sense for the sample to be tied to named individual tourists instead of to seats in the bus even if the stack address name scheme correspond to seat order not tourists order?

It might just be a matter of being careful when writing generative models to not recurse over different order of individual things. Otherwise allowing some kind of manual naming could also be an option.

Or am I interpreting this wrong?

**Comment by stuhlmueller** [comment]
This sounds right to me. Naming choices based on stack addresses is a substantial improvement over sequential naming, but there is no guarantee that it gives the best possible naming scheme. 

In practice, it seems to do pretty well, and in cases with obvious misalignments (as in your tourist example), it is generally possible to rewrite the model in a way that results in more conservative proposals. Here, "conservative" means that the change to the random world caused by a proposal tends to result in a smaller change in posterior probability.

It could be interesting to think about more explicit ways to specify naming schemes. In that case, I'd start by collecting examples of models where naming based on stack addresses goes wrong and where the fix is nontrivial.

**Comment by ngoodman** [comment]
yep, good question and i agree with andreas.

if we had some meaty examples it would spur code changes.

there's an easy and obvious way -- allow users to specify (dynamically
constructed) names as strings at 'sample' statements -- but it's easy to
shoot yourself in the foot that way (using non-unique names)....

-N

**Comment by bessiambre** [comment]
Thank you both for the answers. I get lost in my thought experiments and a discussion helps clear things up a bit. I wonder what the general principle should be for the rules of naming. It seems to me that there may need to be a direct correspondence between the tags and specific instances or parts of instances of things being modelled.

This makes me uneasy as it seems to potentially make the programming language almost too dependant on real world things or modelizations of things and making it less mathematically pure.

But then again, a lot of programming languages implement polymorphism with subtyping or interfaces, which can be seen as crude models of things and often make the instance a basic language concept.

I suppose making the naming scheme relative to some kind of polymorphic instance would be akin to relying on heap address instead of stack address. A new name would be generated on instantiation and when tracing through method calls or functions that are somehow related to an object instance, you could then rely on the name of the instance along with the method name.

This half baked idea brings up all kinds of questions in my mind. Could we have a probabilistic version of polymorphism? Could instances probabilistically "implement" some methods and thus be seen as probabilistically implementing an interface or probabilistically be of a type or subtype? In a way, it seems to have intuitive appeal to how humans organize concepts and maybe even make more sense than overly strict class hierarchies found in nonprobabilistic languages.

I guess back to thinking :-)
