### ISSUE TITLE
Update to latest version of webppl

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/dippl#20]
This requires some adjustment - the live cps and naming transform forms break if I just slot in the latest dev version.

**Comment by null-a** [comment]
I had a quick look at this while testing dippl with the webppl package brach. Applying [thunkify](https://github.com/probmods/webppl/commit/48492d9cb53677de65c8d0fb9da0688bb4d9086b) to cps and addressing seems to fix the problem.

**Comment by stuhlmueller** [comment]
Thanks!
