### ISSUE TITLE
update-webppl script broken

### ISSUE THREAD

**Issue by ngoodman** [probmods/dippl#5]
Running the script results in:

   Resetting webppl to latest remote...
   fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
   Use '--' to separate paths from revisions, like this:
   'git <command> [<revision>...] -- [<file>...]'

**Comment by stuhlmueller** [comment]
Not sure why you're seeing this particular error. It works for me on a fresh repository clone. Did you `git submodule update --init --recursive`?

I did make some changes, but it seems your error happens before the place where I applied changes.

**Comment by ngoodman** [comment]
Ok, got it working -- perhaps I hadn't initialized the submodule after cloning...
