### ISSUE TITLE
"too much recursion" error in firefox

### ISSUE THREAD

**Issue by feste** [probmods/dippl#9]
**In Firefox only**

In
- [Early, incremental evidence](http://dippl.org/chapters/04-factorseq.html) after the line "Similarly the PCFG can be written as:"
- and after the line "Similarly for the PCFG:"
- and also in [Semantic parsing](http://dippl.org/examples/semanticparsing.html), on the line `print(literalListener("all blond people are nice"))`

we get the error:

```
too much recursion
```

**Comment by stuhlmueller** [comment]
Fixed in 64169e84786bf3d4629922a8be9a4b4ac52c4375
